# Generated by Django 5.2.7 on 2025-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('useful_links', 'Links úteis'), ('how_to', 'Como solicitar'), ('phones', 'Telefones úteis'), ('addresses', 'Endereços'), ('videos', 'Vídeos')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_official', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['section', 'locale', 'country', 'is_active', 'sort_order'], name='catalog_res_section_c0931f_idx')],
            },
        ),
    ]
