# Generated by Django 5.2.7 on 2025-11-04 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_resource_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
