# Generated by Django 5.2.7 on 2025-11-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_resource_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('referrer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='catalog.resource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='catalog_cli_created_c6ea72_idx'), models.Index(fields=['link'], name='catalog_cli_link_id_f26431_idx'), models.Index(fields=['locale', 'country'], name='catalog_cli_locale_56452d_idx')],
            },
        ),
    ]
