# Generated by Django 5.2.7 on 2025-11-04 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_clickevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('hero', 'hero'), ('sidebar', 'sidebar'), ('footer', 'footer')], max_length=32)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('target_url', models.URLField(blank=True)),
                ('html_embed', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['position', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['position', 'country', 'is_active'], name='catalog_ads_positio_67669d_idx')],
            },
        ),
    ]
